# Dockerfile — Auto-generated by GitCraft AI
FROM python:3.11-slim

LABEL maintainer="Tanveer"
LABEL description="GitCraft AI generated project"

WORKDIR /app

# System deps
RUN apt-get update && apt-get install -y \
    build-essential curl \
    && rm -rf /var/lib/apt/lists/*

# Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source (secrets must come from environment, not this image)
COPY . .

# Never bake secrets into Docker images.
# Pass them at runtime:
#   docker run -e GROQ_API_KEY=... -e NGROK_AUTH_TOKEN=... your-image
# Or use Docker secrets / Kubernetes secrets.

EXPOSE 8501

HEALTHCHECK --interval=30s --timeout=10s CMD curl -f http://localhost:8501/ || exit 1

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
